# Generated by Django 3.2.6 on 2021-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadgenomeinfo',
            old_name='progress_all',
            new_name='progress_current_value',
        ),
        migrations.RenameField(
            model_name='downloadgenomeinfo',
            old_name='progress_current',
            new_name='progress_total_value',
        ),
        migrations.AddField(
            model_name='downloadgenomeinfo',
            name='log',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='downloadgenomeinfo',
            name='status_log',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='downloadgenomeinfo',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'RUNNING'), ('IDLE', 'IDLE')], default='IDLE', max_length=10),
        ),
    ]
