# Generated by Django 3.2.6 on 2021-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210810_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadgenomeinfo',
            name='progress_current_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
