# Generated by Django 3.2.6 on 2021-08-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_downloadgenomeinfo_progress_current_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadgenomeinfo',
            name='status_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
