# Generated by Django 3.2.6 on 2021-08-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_downloadgenomeinfo_status_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTDBTKInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('IDLE', 'IDLE')], default='IDLE', max_length=10)),
                ('pid', models.CharField(blank=True, max_length=30, null=True)),
                ('progress_total_value', models.IntegerField(blank=True, null=True)),
                ('progress_current_value', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('log', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'gtdbtk_info',
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_type', models.CharField(choices=[('GENOME', 'GENOME'), ('GTDBTK', 'GTDBTK'), ('NONE', 'NONE')], default='NONE', max_length=30)),
                ('last_pid', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'main_info',
            },
        ),
    ]
