# Generated by Django 3.2.6 on 2021-08-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_gtdbtkinfo_maininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('IDLE', 'IDLE')], default='IDLE', max_length=10)),
                ('status_log', models.TextField(blank=True, null=True)),
                ('pid', models.CharField(blank=True, max_length=30, null=True)),
                ('progress_total_value', models.IntegerField(blank=True, null=True)),
                ('progress_current_value', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('log', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'region_info',
            },
        ),
        migrations.AddField(
            model_name='gtdbtkinfo',
            name='status_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='error_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='is_error',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='last_type',
            field=models.CharField(choices=[('GENOME', 'GENOME'), ('GTDBTK', 'GTDBTK'), ('REGION', 'REGION'), ('NONE', 'NONE')], default='NONE', max_length=30),
        ),
    ]
