# Generated by Django 3.2.6 on 2021-08-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210812_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadgenomeinfo',
            name='last_run_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gtdbtkinfo',
            name='last_run_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regioninfo',
            name='last_run_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
